### ISSUE TITLE
Migrate old GoogleCode issues to their respective GitHub projects

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_industrial_issues#1]
Those issues that are still relevant (and haven't been already fixed or invalidated by other work) should be migrated to their respective GitHub projects.

Can be done either manually or semi-automated, see [this](http://beets.radbox.org/blog/github-issues.html) page for instance.

Suggest using a 'gc-hithub-migration' user (or similar) as reporter of the tickets in the case we opt for the automated transfer.

**Comment by shaun-edwards** [comment]
My plan was to manually link back to the remaining issues. A lot of them will be closed with a new Motoman update. The plan is to use the individual github trackers(as you have).  I created this repo because people have complained that they don't know where to submit bugs. They can submit to this one (linked to from our main page) and I will figure out where it goes.

**Comment by gavanderhoorn** [comment]
Most of these issues have been addressed and / or migrated, so closing this.
